export const listOfCuisines = [
  { label: "Any Cuisine", value: "any-cuisine" },
  { label: "Asian Fusion", value: "asian-fusion" },
  { label: "Chinese", value: "chinese" },
  { label: "French", value: "french" },
  { label: "Greek", value: "greek" },
  { label: "Indian", value: "indian" },
  { label: "Italian", value: "italian" },
  { label: "Japanese", value: "japanese" },
  { label: "Lebanese", value: "lebanese" },
  { label: "Malaysian", value: "malaysian" },
  { label: "Mexican", value: "mexican" },
  { label: "Modern European", value: "modern-european" },
  { label: "Modern Australian", value: "modern-australian" },
  { label: "Seafood", value: "seafood" },
  { label: "Sushi", value: "sushi" },
  { label: "Thai", value: "thai" },
  { label: "Vietnamese", value: "vietnamese" },
] as const;
